### ISSUE TITLE
SonarQube 8.4 support?

### ISSUE THREAD

**Issue by n0m0r3pa1n** [devcon5io/mutation-analysis-plugin#41]
According to the page of the plugin: https://www.devcon5.ch/en/products_and_services/products/sonarqube-mutation-plugin/
I was expecting to see the Mutation Analysis tab but it is not there. Is it because the plugin is not supported in 8.4.x?

**Comment by gmuecke** [comment]
The screenshot is a bit dated, the Sonarqube UI changed a bit since then. 
The mutation analysis is now a category under the "Measures" tab.

![grafik](https://user-images.githubusercontent.com/8408106/85304495-1c46d480-b4ac-11ea-9ddf-85566cd04d48.png)

I'm running it on SQ 8.3.1, so I assume it should run on 8.4 too, but I haven't tested it

You may also check the settings, if the plugin is working in general, you should see an entry in the Configurations.
![grafik](https://user-images.githubusercontent.com/8408106/85304854-88293d00-b4ac-11ea-9322-ed8b2ff0490c.png)

**Comment by n0m0r3pa1n** [comment]
Basically we figured it out. For some reason the Mutation Analysis tab is displayed for the master branch only, it is not displayed for any other branch (in our case PR branches).
