### ISSUE TITLE
SonarQube 7.9.1 warning during analysis

### ISSUE THREAD

**Issue by markluebbehuesen** [devcon5io/mutation-analysis-plugin#42]
Hello,

I get the following warning during the sonarqube analysis, but 7 rules are activated in my profile

**[WARNING] /!\ At least one Mutation Analysis rule needs to be activated the current profile.**

thanks,
Mark

**Comment by gmuecke** [comment]
Hi Mark,
have you checked, wether the activated rules are "mutation operator" rules? and wether you applied that profile to your project? 

Gerald

**Comment by markluebbehuesen** [comment]
Hi Gerald,

attached you will see a screenshot of the assigned profile. 
7 "mutation operator" rules are activated and that profile is applied to the project.

![pitest](https://user-images.githubusercontent.com/40758526/85682537-aff6eb80-b6cc-11ea-9e02-7afdc199cb07.JPG)

Does the branch type matter? I am currently working with the short lived branch.

We use the Developer Edition of SonarQube.

thx,
Mark

**Comment by gmuecke** [comment]
It seems, the analysis is not working / possible on a short-lived branch. See also https://github.com/devcon5io/mutation-analysis-plugin/issues/41 

I don't have a developer version at hand, so I can reproduce the issue on my side.

**Comment by esmiralhaibm** [comment]
Hi people,

can someone confirm the compatibility with Sonarqube 7.9.1?

Thank you!
Luiz

**Comment by FelixLee888** [comment]
@gmuecke may I know if there is any update on this issue?  We upgraded our sonar to 7.9 and found that this plugin is not working anymore, any hints that I could fix the issue?

**Comment by gmuecke** [comment]
As said before, I don't have the SQ Developer Edition at hand, so I can't try to reproduce anything that happens when using any of its features - like analysis on branches. 
I use the plugin on a fairly recent 8.x version of the community edition - without any problems. 
I haven't tested with 7.9 for a while, so it would be *_really_* helpfull, if someone would take the time to create a proper error description, how to reproduce and probably provide a proper reproducer project so I don't have to hours to figure it out myself. 
If you don't have time for this, you may consider commercial support, so I can free up some time for a proper analysis. 
What are your thoughts on this?
